### PR TITLE
Add installed jre

### PR DESCRIPTION
**Pull request by scottresnik**
I added functionality to specify additional JRE's to be included in the workspace.

### CODE REVIEW

**Comment by nedtwigg** [comment]
For future reference, you can just run `gradlew spotlessApply` and all the formatting issues will be resolved, including line ending problems.  As-is, I can't tell what these commits actually do because of line ending and formatting mixups.  Do you mind running `spotlessApply` and squashing them all into one?  If you don't know git-fu, I can do it for you.

**Comment by nedtwigg** [comment]
Sorry, should have opened with "looks like a great feature!".  I'm excited to merge it in :)

**Comment by scottresnik** [comment]
Missed spotless on the last commit.  Squashed the formatting commits.  Left the meat.  I can squash further, if desired.

**Comment by nedtwigg** [comment]
Thanks a ton for the great contribution!  A couple questions:

- How can I credit you in the [acknowledgements](https://github.com/diffplug/goomph#acknowledgements)?  Scott Resnik?  Would you like me to link to your github, twitter, elsewhere?
- Shall I release this as `3.5.0`, or is there more coming down the pike that you'd like to be included?

**Comment by scottresnik** [comment]
* RE: [acknowledgements](https://github.com/diffplug/goomph#acknowledgements): I guess my name + github is fine.  Just glad I could make a contribution to a useful plugin.
* RE: `3.5.0`: Ship it :).

**Pull request merged**
