### PR TITLE
Fix CI by fixing NativeDeps swt version and removing CategoryPublisherTest.java

### LINKED ISSUE #168: NativeDepsPluginTest requires Java 11
When I run `./gradlew build` using Java 8 I get this error:

```
com.diffplug.gradle.swt.NativeDepsPluginTest > assertPluginWorks FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /var/folders/d9/hsnvfz416qz37w3_v1kpj5pw0000gn/T/junit3217243612717905599 with arguments [test, --stacktrace]

    Output:

    > Configure project :
    p2AsMaven eclipse-swt-deps is dirty.
    Initalizing maven group eclipse-swt-deps from p2
    Only needs to be done once, future builds will be much faster
    p2AsMaven eclipse-swt-deps installing from p2
    Buildfile: /var/folders/d9/hsnvfz416qz37w3_v1kpj5pw0000gn/T/goomph-ant-build8045953443048996787.xml
    [p2.mirror] Messages while mirroring artifact descriptors.
    BUILD SUCCESSFUL

    BUILD SUCCESSFUL
    Total time: 43 seconds
    p2AsMaven eclipse-swt-deps creating maven repo
    p2AsMaven eclipse-swt-deps is complete.

    > Task :compileJava NO-SOURCE
    > Task :processResources NO-SOURCE
    > Task :classes UP-TO-DATE

    > Task :compileTestJava FAILED
    /private/var/folders/d9/hsnvfz416qz37w3_v1kpj5pw0000gn/T/junit3217243612717905599/src/test/java/undertest/NeedsSwt.java:8: error: cannot access Display
                Assert.assertEquals("org.eclipse.swt.widgets.Display", org.eclipse.swt.widgets.Display.class.getName());
                                                                                              ^
      bad class file: /private/var/folders/d9/hsnvfz416qz37w3_v1kpj5pw0000gn/T/junit3217243612717905599/build/p2asmaven/maven/eclipse-swt-deps/org.eclipse.swt.cocoa.macosx.x86_64/3.117.0.v20210906-0842/org.eclipse.swt.cocoa.macosx.x86_64-3.117.0.v20210906-0842.jar(org/eclipse/swt/widgets/Display.class)
        class file has wrong version 55.0, should be 52.0
        Please remove or make sure it appears in the correct subdirectory of the classpath.
    1 error

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileTestJava'.
    > Compilation failed; see the compiler error output for details.
```

I did not look at all the details, but I can imagine that the SWT version used by the plugin inside the test is now requiring Java 11.

### PR DESCRIPTION
**Pull request by jmini**
Fixes #168

### CODE REVIEW

**Comment by jmini** [comment]
No need to publish a new version of the library after this merge.

**Comment by jmini** [comment]
I do not see CI build results…

**Comment by jmini** [comment]
I found some CI results here:
https://app.circleci.com/pipelines/github/jmini/goomph/8/workflows/f7a2e027-72f1-4e9b-b002-f3fbe58300ec/jobs/18

It is not that simple:

Now the Java 11 build is failing with:
```
Caused by: java.lang.Error: p2asmaven requires JRE 8, this is JRE 11
	at com.diffplug.gradle.eclipserunner.EquinoxLauncher.<init>(EquinoxLauncher.java:69)
	... 6 more
```

What should I do?

**Comment by nedtwigg** [comment]
I completely bastardized your PR, but CI now works on Java 8 and Java 11, which I think was your core issue. Let me know if I missed the point.

**Comment by jmini** [comment]
This is exactly what I needed.

Thank you a lot for this.

**Pull request merged**
